name: About RoyLinKung
url: http://about.roykung.com
description: "林昆彥 (RoyLinKung). I'm a dreamer, singer and Basketball player, loving jogging, reading and cooking, now running a startup in Taipei, Taiwan."
pygments: true

profiles:
  - name: "RoyLinKung"
    url: http://about.roykung.com
    external: true

projects:
  - name: Co-Founder of Credarp Inc
    description: "We make web and native mobile app at Credarp. Our product is elbum.in, a analytics tool for sport teams to track, collect and organize their statistics. We also develop Ruby on Rails and iOS projects.  The company has been founded at 2013 July. I run it with my partner Brian, Labrada and our 2 developers. "
    url: http://facebook.com/credarp
    external: true
    published_at: '2013-07 ~ present'
  - name: Founder of Dreamers' Day
    description: "Dreamers' Day is the biggest student startup community in Taiwan. Brian and I started it because we believe that student should have entrepreneurship.  There had been 5 demo shows and  20 meet ups both in Taipei and Tainan, and over 300 students participanted in it."
    url: http://dreamersday.tw
    external: true
    published_at: '2011-10 ~ 2013-05'
  - name: Product Manager of Gabble
    description: "Gabble is a real time QA system base on people's trusted network. I worked with my friend Kenzou, Robbie and Brian to build a awesome product. I had a great time and get a lot of experience in this 8 month at Gabble."
    url: http://blog.gabble.me 
    external: true
    published_at: '2012-04 ~ 2012-11' 

organizations:
  - name: SITW (students in Taiwan)
    url: http://github.com/sitw
    description: "My friends and I are organizers. We wanna promote the sprits of open source to all students, so we publish lots of things on github in order to attract others."

experiences:
  - company_name: Womany
    company_url: http://womany.net/
    external: true
    title: Front-end developer
    location: "Taipei, Taiwan"
    duration: "2013-07 ~ present"
  - company_name: Cardinal Blue
    company_url: http://cardinalblue.com/
    external: true
    title: User experience intern
    location: "Taipei, Taiwan"
    duration: "2012-07 ~ 2012-09"
  - company_name: Asus
    company_url: http://www.asus.com/tw/
    external: true
    title: Campus Officer
    location: "Taipei, Taiwan"
    duration: "2011-06 ~ 2012-06"

educations:
  - school_name: National Taiwan University
    school_url: http://www.ntu.edu.tw/english/
    external: true
    degree: BS
    field: BioIndustry Communaction and Development
    duration: "2009-07 ~ 2013-06"

social_networks:
  - name: Facebook
    url: https://www.facebook.com/royLinKung
    icon: icon-facebook
    external: true
  - name: Twitter
    url: https://twitter.com/roylinkung
    icon: icon-twitter
    external: true
  - name: LinkedIn
    url: http://www.linkedin.com/in/roylinkung
    icon: icon-linkedin
    external: true
  - name: contact
    url: mailto:qwer789852@gmail.com
    icon: icon-inbox
    external: true

slides:
  - name: Social Traction For Apps
    url: http://www.slideshare.net/roykung/social-traction-for-app
    external: true
  - name: Dreamers' day the first year review
    url: http://www.slideshare.net/roykung/dreamers-day-the-first-year-review
    external: true
  - name: Airbnb find a better place to stay
    url: http://www.slideshare.net/roykung/casestudyonairbnb
    external: true  
  - name: Dreamers' Day @NCKU
    url:  http://www.slideshare.net/roykung/dreamers-day-3-ncku
    external: true
  - name: The entrepreneurship in University
    url: http://www.slideshare.net/roykung/bicd-present
    external: true

skills:
  - name: Ruby
    duration: "2011 ~ present"
  - name: Java
    duration: "2012-06 ~ 2013-06"

blogs:
  - name: Blog
    description: "Startup, Product Design, Marketing"
    url: http://roykung.com
    external: true
  - name: Life
    description: "Life, Basketball, Realationship"
    url: http://life.roykung.com
    external: true


exclude: [".rvmrc", ".rbenv-version", ".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]

